# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [ ]:
dataset = pd.read_csv("Data.csv")
# print(dataset)
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
#  prints missing values in each column of the dataset
print(dataset.isnull().sum())
# prints total missing values in the dataset
print(dataset.isnull().sum().sum())

: 

## Taking care of missing data

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
# print(X)
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

## Encoding categorical data

### Encoding the Independent Variable

In [15]:
# one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# transformers parameter accepts values - kind of transformation,class that will do the encoding, indexes of columns
# we can also create a list of columns that have categorical data and pass that to indexes

# remainder parameter decides what to do to columns which are not transformed
ct = ColumnTransformer(transformers=[('Encoder',OneHotEncoder(),[0])],remainder='passthrough')
# fit transform returns a new array with encoding but it doesnt return output as numpy array
X = np.array(ct.fit_transform(X))

### Encoding the Dependent Variable

In [14]:
# label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y=le.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


## Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])